language: python
python:
- '2.7'
env:
- DJANGO_SETTINGS_MODULE='neatpix.settings.testing'
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- npm install bower
script:
- bower install
- python neatpix/manage.py collectstatic --noinput --settings=neatpix.settings.testing
- coverage run --source=webapp neatpix/manage.py test neatpix --settings=neatpix.settings.testing
  -s
after_success:
- coveralls
deploy:
  provider: heroku
  buildpack:
    - node
    - python
  api_key:
    secure: JRgLF1LupJ2XHKf6gmOVNNhr9zMfOYi8uOKjDmMTV43VP79+xmwD1euBbWYFuGeAP+zB1K733hyaJ883655FdSRkj4j4pt1GerAh2Tago9C89Z1IcGwmEOaw5lR+OfMJwSCutEfhdOqfP//MaAVjOt8Qrgoef8xZ+jMHub5Owz11kLFkFQ9rEh/+kF26zH23JadLjxNTRPPud0hNyqz1GUqGSPTR25ge7ssBPxZ0OWLjjelDseJh+CJ54qdd1eYnf3oftxMAgyA6pfLz9t0Of645e/iPwniQFSONkUgngpkrkHBVDV3f327exfq59bO4QQHdZML6CBLe0Vwa1tNlDT5XP5+FIWI3dpsfSAK96hhADgvVEQL1ZCQnN2FIv4QDG2yCbfP1aFvbBHZsk1RGdBZbE3/NdogogEMbtuxzTBMrWE3xMNda3f4k4QMk9BZhG1UomxmoH2oSc5pUprb6fPgfq6bzWcsxyWDqOdxttHO3F+QRCIM6aopX0cxBzM8g/FH+Fbp8LnkJgnBCAc1Bk1jXgZq6ORTlSpL7J5im4mz1AVWXxD2F0rtxCbaSKnKe1EArVRFgigddb4MPMiOsRDGKK30WoCf9XM7Szgk8FepScJQywfctORGOL48NKS0BfOZPSZU5pIlpesjsxrWptDHhWVv+Rs32kLa1pr2TWsY=
  app:
    develop: neatpix
    master: neatpix
  on:
    all_branches: true
  run:
    - export DJANGO_SETTINGS_MODULE=neatpix.settings.staging
    - python neatpix/manage.py collectstatic --noinput --settings=neatpix.settings.staging
    - python neatpix/manage.py makemigrations --settings=neatpix.settings.staging
    - python neatpix/manage.py migrate auth --settings=neatpix.settings.staging
    - python neatpix/manage.py migrate --settings=neatpix.settings.staging
after_deploy:
  - "heroku ps:scale web=1 --app neatpix"